# Generated by Django 5.2.3 on 2025-06-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapaproducao',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Etapa de Produção', 'verbose_name_plural': 'Etapas de Produção'},
        ),
        migrations.AlterModelOptions(
            name='historicoetapas',
            options={'ordering': ['start_time'], 'verbose_name': 'Histórico de Etapa', 'verbose_name_plural': 'Históricos de Etapas'},
        ),
        migrations.AlterModelOptions(
            name='ordemproducao',
            options={'ordering': ['start_date'], 'verbose_name': 'Ordem de Produção', 'verbose_name_plural': 'Ordens de Produção'},
        ),
    ]
