# Generated by Django 5.2.3 on 2025-06-29 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endereco_destino', models.CharField(max_length=255)),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('data_prevista_entrega', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ROTA', 'Em Rota'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('transportadora', models.CharField(max_length=100)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='comercial.pedidovenda')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['data_prevista_entrega', 'status'],
            },
        ),
        migrations.CreateModel(
            name='RotaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entregador', models.CharField(max_length=255)),
                ('data_rota', models.DateField()),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('entregas', models.ManyToManyField(related_name='rotas', to='logistica.entrega')),
            ],
            options={
                'verbose_name': 'Rota de Entrega',
                'verbose_name_plural': 'Rotas de Entrega',
                'ordering': ['data_rota', 'status'],
            },
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['pedido'], name='logistica_e_pedido__4e17ac_idx'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['status'], name='logistica_e_status_b031a1_idx'),
        ),
        migrations.AddIndex(
            model_name='rotaentrega',
            index=models.Index(fields=['entregador', 'data_rota'], name='logistica_r_entrega_13f068_idx'),
        ),
        migrations.AddIndex(
            model_name='rotaentrega',
            index=models.Index(fields=['status'], name='logistica_r_status_406099_idx'),
        ),
    ]
