# Generated by Django 5.2.3 on 2025-06-29 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produzir', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio_prevista', models.DateField()),
                ('data_fim_prevista', models.DateField()),
                ('data_inicio_real', models.DateField(blank=True, null=True)),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('unidade_medida', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='EtapaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_etapa', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('sequencia', models.IntegerField()),
                ('data_inicio_prevista', models.DateField()),
                ('data_fim_prevista', models.DateField()),
                ('data_inicio_real', models.DateField(blank=True, null=True)),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='producao.ordemproducao')),
            ],
            options={
                'verbose_name': 'Etapa de Produção',
                'verbose_name_plural': 'Etapas de Produção',
                'ordering': ['sequencia'],
            },
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.produto'),
        ),
    ]
