# Generated by Django 5.2.3 on 2025-07-01 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_ordemproducao_pedido_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducaoObservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OBSERVACAO', 'Observação'), ('RETRABALHO', 'Retrabalho')], max_length=50)),
                ('descricao', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producao_observacoes', to='producao.ordemproducao')),
            ],
            options={
                'verbose_name': 'Observação/Retrabalho da Ordem de Produção',
                'verbose_name_plural': 'Observações/Retrabalhos das Ordens de Produção',
                'ordering': ['-data_registro'],
            },
        ),
    ]
