# Generated by Django 5.2.3 on 2025-06-29 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcp', '0002_alter_etapaproducao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('KG', 'Kilogramas'), ('UN', 'Unidades'), ('M', 'Metros'), ('L', 'Litros')], max_length=10)),
                ('minimum_stock', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Matéria Prima',
                'verbose_name_plural': 'Matérias Primas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoAcabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('production_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Produto Acabado',
                'verbose_name_plural': 'Produtos Acabados',
                'ordering': ['-production_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('EM_PRODUCAO', 'Em Produção'), ('AGUARDANDO_QUALIDADE', 'Aguardando Qualidade'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDO', 'Concluído')], default='EM_PRODUCAO', max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_em_processo', to='pcp.ordemproducao')),
            ],
            options={
                'verbose_name': 'Produto em Processo',
                'verbose_name_plural': 'Produtos em Processo',
                'ordering': ['-created_at'],
            },
        ),
    ]
