# Generated by Django 5.2.3 on 2025-06-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='type',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
