# Generated by Django 5.2.3 on 2025-06-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_materiaprima_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='local',
            field=models.CharField(default='Almoxarifado', max_length=255),
        ),
    ]
