# Generated by Django 5.2.3 on 2025-07-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_materiaprima_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='metragem_por_rolo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Metragem por rolo (preenchido apenas para unidade 'Rolo')", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='quantidade_rolos',
            field=models.IntegerField(blank=True, help_text="Quantidade de rolos (preenchido apenas para unidade 'Rolo')", null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unit',
            field=models.CharField(choices=[('KG', 'Kilogramas'), ('UN', 'Unidades'), ('M', 'Metros'), ('L', 'Litros'), ('ROLO', 'Rolo'), ('CAIXA', 'Caixa')], max_length=10),
        ),
    ]
