# Generated by Django 5.2.3 on 2025-07-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_materiaprima_metragem_por_rolo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='type',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='unit',
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='categoria_subtipo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='cor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='tipo_produto',
            field=models.CharField(choices=[('TECIDO', 'Tecido'), ('LINHA', 'Linha'), ('ETIQUETA', 'Etiqueta'), ('BOTAO', 'Botão'), ('FIO_DE_BORDADO', 'Fio de Bordado'), ('TERMOCOLANTE', 'Termocolante'), ('GOLA_CANALETADA', 'Gola canaletada'), ('EMBALAGEM', 'Embalagem')], default='TECIDO', max_length=50),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='unidade_medida',
            field=models.CharField(choices=[('METRO', 'Metro'), ('UNIDADE', 'Unidade'), ('GRAMA', 'Grama'), ('ROLO', 'Rolo'), ('CAIXA', 'Caixa'), ('LITRO', 'Litro')], default='UNIDADE', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade'),
        ),
    ]
