# Generated by Django 5.2.3 on 2025-07-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_materiaprima_type_remove_materiaprima_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='quantidade_caixas',
            field=models.IntegerField(blank=True, help_text="Quantidade de caixas (preenchido apenas para unidade 'Caixa')", null=True),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='quantidade_por_caixa',
            field=models.IntegerField(blank=True, help_text="Quantidade de unidades por caixa (preenchido apenas para unidade 'Caixa')", null=True),
        ),
    ]
