# Generated by Django 5.2.3 on 2025-07-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_materiaprima_quantidade_caixas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='metros_por_tubo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Metragem por tubo (preenchido apenas para unidade 'Tubo')", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='quantidade_tubos',
            field=models.IntegerField(blank=True, help_text="Quantidade de tubos (preenchido apenas para unidade 'Tubo')", null=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unidade_medida',
            field=models.CharField(choices=[('METRO', 'Metro'), ('UNIDADE', 'Unidade'), ('GRAMA', 'Grama'), ('ROLO', 'Rolo'), ('CAIXA', 'Caixa'), ('LITRO', 'Litro'), ('TUBO', 'Tubo')], default='UNIDADE', max_length=20),
        ),
    ]
