# Generated by Django 5.2.3 on 2025-07-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_materiaprima_metros_por_tubo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='tipo_produto',
            field=models.CharField(choices=[('TECIDO', 'Tecido'), ('LINHA', 'Linha'), ('ETIQUETA', 'Etiqueta'), ('BOTAO', 'Botão'), ('FIO_DE_BORDADO', 'Fio de Bordado'), ('TERMOCOLANTE', 'Termocolante'), ('GOLA_CANALETADA', 'Gola canaletada'), ('GOLAS', 'Golas'), ('EMBALAGEM', 'Embalagem')], default='TECIDO', max_length=50),
        ),
    ]
