# Generated by Django 5.2.3 on 2025-07-08 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0013_pedidovenda_em_espera_alter_pedidovenda_status'),
        ('estoque', '0008_alter_materiaprima_tipo_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='tipo_produto',
            field=models.CharField(choices=[('TECIDO', 'Tecido'), ('LINHA', 'Linha'), ('ETIQUETA', 'Etiqueta'), ('BOTAO', 'Botão'), ('FIO_DE_BORDADO', 'Fio de Bordado'), ('TERMOCOLANTE', 'Termocolante'), ('GOLAS', 'Golas'), ('EMBALAGEM', 'Embalagem')], default='TECIDO', max_length=50),
        ),
        migrations.CreateModel(
            name='HistoricoUsoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_utilizacao', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_uso', to='estoque.materiaprima')),
                ('pedido_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_materiais_usados', to='comercial.pedidovenda')),
            ],
            options={
                'verbose_name': 'Histórico de Uso de Material',
                'verbose_name_plural': 'Históricos de Uso de Materiais',
                'ordering': ['-data_utilizacao'],
            },
        ),
    ]
