# Generated by Django 5.2.3 on 2025-07-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_alter_materiaprima_tipo_produto_historicousomaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicousomaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_uso', to='estoque.materiaprima'),
        ),
    ]
