# Generated by Django 5.2.3 on 2025-07-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_historicousomaterial_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='local',
            field=models.CharField(choices=[('ALMOXARIFADO', 'Almoxarifado'), ('MEZANINO', 'Mezanino'), ('PRODUCAO', 'Produção')], default='ALMOXARIFADO', max_length=255),
        ),
    ]
