# Generated by Django 5.2.3 on 2025-07-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_alter_materiaprima_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='tipo_produto',
            field=models.CharField(default='TECIDO', max_length=50),
        ),
    ]
