# Generated by Django 5.2.3 on 2025-06-29 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcp', '0002_alter_etapaproducao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistInspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_peca', models.CharField(max_length=100)),
                ('itens', models.TextField(help_text='Lista de itens do checklist, separados por linha ou JSON.')),
                ('setor', models.CharField(choices=[('RECEBIMENTO', 'Recebimento'), ('PRODUCAO', 'Produção'), ('FINALIZACAO', 'Finalização'), ('EXPEDICAO', 'Expedição')], max_length=20)),
            ],
            options={
                'verbose_name': 'Checklist de Inspeção',
                'verbose_name_plural': 'Checklists de Inspeção',
                'ordering': ['setor', 'tipo_peca'],
            },
        ),
        migrations.CreateModel(
            name='Falha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.TextField()),
                ('tipo_falha', models.CharField(choices=[('DEFEITO', 'Defeito'), ('NAO_CONFORMIDADE', 'Não Conformidade'), ('ERRO_OPERACIONAL', 'Erro Operacional'), ('OUTRO', 'Outro')], default='DEFEITO', max_length=30)),
                ('resolvido', models.BooleanField(default=False)),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='falhas', to='pcp.etapaproducao')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falhas', to='pcp.ordemproducao')),
            ],
            options={
                'verbose_name': 'Falha',
                'verbose_name_plural': 'Falhas',
                'ordering': ['-created_at', 'resolvido'],
            },
        ),
        migrations.CreateModel(
            name='Retrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operador_responsavel', models.CharField(max_length=255)),
                ('tempo_gasto', models.DurationField()),
                ('data_retrabalho', models.DateTimeField(auto_now_add=True)),
                ('falha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retrabalho', to='qualidade.falha')),
            ],
            options={
                'verbose_name': 'Retrabalho',
                'verbose_name_plural': 'Retrabalhos',
                'ordering': ['-data_retrabalho'],
            },
        ),
        migrations.AddIndex(
            model_name='falha',
            index=models.Index(fields=['ordem', 'etapa'], name='qualidade_f_ordem_i_15dd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='falha',
            index=models.Index(fields=['tipo_falha', 'resolvido'], name='qualidade_f_tipo_fa_07f331_idx'),
        ),
        migrations.AddIndex(
            model_name='retrabalho',
            index=models.Index(fields=['operador_responsavel', 'data_retrabalho'], name='qualidade_r_operado_104a04_idx'),
        ),
    ]
