# Generated by Django 5.2.3 on 2025-06-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='etapas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
