# Generated by Django 5.2.3 on 2025-06-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_pedidovenda_etapas_pedidovenda_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta')], default='NORMAL', max_length=20),
        ),
    ]
