# Generated by Django 5.2.3 on 2025-07-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_itempedido'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='cor_estampa_bordado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='cor_tecido',
            field=models.CharField(default='BRANCO', max_length=50),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='costura_especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='local_bordado',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='modelo_camisa',
            field=models.CharField(blank=True, choices=[('GOLA_POLO', 'Gola Polo'), ('GOLA_CARECA', 'Gola Careca'), ('SOCIAL', 'Social'), ('BABY_LOOK', 'Baby Look'), ('REGATA', 'Regata')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='observacoes_adicionais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='tamanhos',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='tipo_estampa_bordado',
            field=models.CharField(choices=[('NENHUM', 'Nenhum'), ('BORDADO', 'Bordado'), ('SILK_SCREEN', 'Silk Screen'), ('SUBLIMACAO', 'Sublimação')], default='NENHUM', max_length=50),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='tipo_tecido',
            field=models.CharField(blank=True, choices=[('MALHA_PV', 'Malha PV'), ('ALGODAO', 'Algodão'), ('DRY_FIT', 'Dry Fit'), ('VISCOLYCRA', 'Viscolycra')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='quantidade_pecas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='prioridade',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='quantidade',
        ),
    ]
