# Generated by Django 5.2.3 on 2025-07-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_alter_itempedido_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='gola_subtipo',
            field=models.CharField(blank=True, help_text='Subtipo da gola, se o modelo for de gola', max_length=255, null=True),
        ),
    ]
