# Generated by Django 5.2.3 on 2025-07-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_itempedido_gola_subtipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='modelo_camisa',
            field=models.CharField(blank=True, choices=[('CAMISETA_TRADICIONAL', 'Camiseta Tradicional'), ('GOLA_POLO', 'Gola Polo'), ('GOLA_CARECA', 'Gola Careca'), ('SOCIAL', 'Social'), ('BABY_LOOK', 'Baby Look'), ('REGATA', 'Regata')], max_length=50, null=True),
        ),
    ]
