# Generated by Django 5.2.3 on 2025-07-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_alter_itempedido_modelo_camisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidovenda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('PRODUCAO', 'Em Produção')], default='PENDENTE', max_length=20),
        ),
    ]
