# Generated by Django 5.2.3 on 2025-07-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_alter_pedidovenda_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='cor_estampa_bordado',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='cor_tecido',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='costura_especial',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='gola_subtipo',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='local_bordado',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='modelo_camisa',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='observacoes_adicionais',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='tipo_estampa_bordado',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='tipo_tecido',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='bordado',
            field=models.TextField(blank=True, help_text='Detalhes do bordado', null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='corpo_costa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='corpo_frente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição adicional opcional', null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='gola',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='manga',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='materiais',
            field=models.JSONField(default=list, help_text="Lista de materiais e suas quantidades. Ex: [{'material_id': 1, 'quantidade': 2.5}]"),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='modelo',
            field=models.CharField(default='Modelo Padrão', help_text="Ex: 'Gola Polo Tradicional' ou 'Calça Jogger Masculina'", max_length=255),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='tipo',
            field=models.CharField(choices=[('CAMISA', 'Camisa'), ('CALCA', 'Calça')], default='CAMISA', max_length=10),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='tamanhos',
            field=models.JSONField(default=dict, help_text="Grade de tamanhos e quantidades. Ex: {'P': 10, 'M': 20}"),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('PRODUCAO', 'Em Produção'), ('ESTOQUE', 'Estoque'), ('CORTE', 'Corte'), ('ESTAMPARIA', 'Estamparia'), ('BORDADO', 'Bordado'), ('COSTURA', 'Costura'), ('ACABAMENTO', 'Acabamento'), ('EMBALAGEM', 'Embalagem')], default='PENDENTE', max_length=20),
        ),
    ]
