# Generated by Django 5.2.3 on 2025-07-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_remove_itempedido_cor_estampa_bordado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
