# Generated by Django 5.2.3 on 2025-07-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_alter_pedidovenda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='em_espera',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('PRODUCAO', 'Em Produção'), ('ESTOQUE', 'Estoque'), ('CORTE', 'Corte'), ('ESTAMPARIA', 'Estamparia'), ('BORDADO', 'Bordado'), ('COSTURA', 'Costura'), ('ACABAMENTO', 'Acabamento'), ('EMBALAGEM', 'Embalagem'), ('MATERIAIS_CONFIRMADOS', 'Materiais Confirmados'), ('MATERIAIS_INCOMPLETOS', 'Materiais Incompletos')], default='PENDENTE', max_length=30),
        ),
    ]
