# Generated by Django 5.2.3 on 2025-07-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0013_pedidovenda_em_espera_alter_pedidovenda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='materiais_baixados',
            field=models.BooleanField(default=False),
        ),
    ]
