# Generated by Django 5.2.3 on 2025-07-09 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0014_pedidovenda_materiais_baixados'),
        ('estoque', '0009_alter_materiaprima_tipo_produto_historicousomaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text='Ex: Camisa Polo, Camisa Social, Calça Jeans', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('CAMISA', 'Camisa'), ('CALCA', 'Calça')], default='CAMISA', max_length=10)),
            ],
            options={
                'verbose_name': 'Modelo de Produto',
                'verbose_name_plural': 'Modelos de Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='modelo',
            field=models.CharField(blank=True, help_text="Ex: 'Gola Polo Tradicional' ou 'Calça Jogger Masculina'", max_length=255),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='modelo_base',
            field=models.ForeignKey(blank=True, help_text='Modelo base para ficha técnica de materiais', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.modeloproduto'),
        ),
        migrations.CreateModel(
            name='MaterialModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Quantidade do material para produzir uma unidade do modelo', max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='estoque.materiaprima')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='comercial.modeloproduto')),
            ],
            options={
                'verbose_name': 'Material do Modelo',
                'verbose_name_plural': 'Materiais do Modelo',
                'unique_together': {('modelo', 'material')},
            },
        ),
    ]
