# Generated by Django 5.2.3 on 2025-07-09 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0015_modeloproduto_alter_itempedido_modelo_and_more'),
        ('estoque', '0009_alter_materiaprima_tipo_produto_historicousomaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tamanho', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=3)),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Consumo do material para este tamanho', max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_modelos', to='estoque.materiaprima')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_materiais', to='comercial.modeloproduto')),
            ],
            options={
                'verbose_name': 'Consumo de Material por Tamanho',
                'verbose_name_plural': 'Consumos de Materiais por Tamanho',
                'ordering': ['modelo', 'tamanho'],
                'unique_together': {('modelo', 'tamanho', 'material')},
            },
        ),
        migrations.DeleteModel(
            name='MaterialModelo',
        ),
    ]
