# Generated by Django 5.2.3 on 2025-07-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0018_alter_consumomaterial_material'),
        ('estoque', '0010_alter_historicousomaterial_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumomaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_modelos', to='estoque.materiaprima'),
        ),
    ]
