# Generated by Django 5.2.3 on 2025-07-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0019_alter_consumomaterial_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloproduto',
            name='cor',
            field=models.CharField(blank=True, default='', help_text='Cor principal do modelo de produto', max_length=100),
        ),
    ]
