# Generated by Django 5.2.3 on 2025-07-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_modeloproduto_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloproduto',
            name='cor',
        ),
    ]
