# Generated by Django 5.2.3 on 2025-07-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0021_remove_modeloproduto_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='materiais_necessarios',
            field=models.JSONField(blank=True, default=list, help_text='Lista consolidada de materiais necessários para o pedido'),
        ),
    ]
